[package]
name = "byteview"
description = "Thin, immutable zero-copy slice type"
license = "MIT OR Apache-2.0"
version.workspace = true
edition.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
categories = ["data-structures"]
keywords = ["german-string", "string-view", "byte-slice"]

[features]
default = []
serde = ["dep:serde"]

[dependencies]
serde = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true }
